//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertExcelToDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectingPipe
    {
        public int id { get; set; }
        public Nullable<int> targetId { get; set; }
        public string CPI_NUM { get; set; }
        public string IN_MHNUM { get; set; }
        public string IN_PINUM { get; set; }
        public Nullable<decimal> CPI_WID { get; set; }
        public Nullable<decimal> CPI_HEI { get; set; }
        public Nullable<decimal> CPI_LENG { get; set; }
        public string PI_MAT { get; set; }
        public Nullable<decimal> US_BLE { get; set; }
        public Nullable<decimal> IN_TDIS { get; set; }
        public string CONS_ID { get; set; }
        public string CITY_ID { get; set; }
        public string NOTE { get; set; }
        public string NOTE2 { get; set; }
        public string NOTE3 { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
    }
}
