//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertExcelToDB.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPAMIEntities : DbContext
    {
        public CPAMIEntities()
            : base("name=CPAMIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConnectingPipe> ConnectingPipe { get; set; }
        public virtual DbSet<ContentData> ContentData { get; set; }
        public virtual DbSet<ContentImg> ContentImg { get; set; }
        public virtual DbSet<GIsMenu> GIsMenu { get; set; }
        public virtual DbSet<PipeCableAttach> PipeCableAttach { get; set; }
        public virtual DbSet<PipeCross> PipeCross { get; set; }
        public virtual DbSet<PipeOther> PipeOther { get; set; }
        public virtual DbSet<PipeSilt> PipeSilt { get; set; }
        public virtual DbSet<PipeUnableWalk> PipeUnableWalk { get; set; }
        public virtual DbSet<RainCompletedManhole> RainCompletedManhole { get; set; }
        public virtual DbSet<RainCompletedPipeline> RainCompletedPipeline { get; set; }
        public virtual DbSet<RainwaterDitch> RainwaterDitch { get; set; }
        public virtual DbSet<SetWells> SetWells { get; set; }
        public virtual DbSet<TableColumnText> TableColumnText { get; set; }
        public virtual DbSet<TaiwanCode> TaiwanCode { get; set; }
    }
}
