//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertExcelToDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PipeUnableWalk
    {
        public int id { get; set; }
        public Nullable<int> targetId { get; set; }
        public string P_NO { get; set; }
        public string CHART_NO { get; set; }
        public string TOWN_NAME { get; set; }
        public string TOWN_ID { get; set; }
        public string MSHED { get; set; }
        public string DIS_STMH { get; set; }
        public string DIS_NUM { get; set; }
        public string STATEM { get; set; }
        public string INV_DATE { get; set; }
        public string INV_GRP { get; set; }
        public string DEV_OK { get; set; }
        public string DEV_DATE { get; set; }
        public string DEV_GRP { get; set; }
        public string PICTURE { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
    }
}
