//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertExcelToDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RainCompletedPipeline
    {
        public int id { get; set; }
        public Nullable<int> targetId { get; set; }
        public string SSEW_CAT { get; set; }
        public string PI_NUM { get; set; }
        public string US_MH { get; set; }
        public string DS_MH { get; set; }
        public string PI_TYP { get; set; }
        public string PI_CLASS { get; set; }
        public Nullable<decimal> PI_WIDT { get; set; }
        public Nullable<decimal> PI_WIDB { get; set; }
        public Nullable<decimal> PI_HEI { get; set; }
        public Nullable<decimal> PI_LENG { get; set; }
        public string PI_MAT { get; set; }
        public Nullable<decimal> PI_SLOP { get; set; }
        public Nullable<decimal> DES_FLOW { get; set; }
        public Nullable<decimal> DES_VELO { get; set; }
        public Nullable<decimal> US_BLE { get; set; }
        public Nullable<decimal> DS_BLE { get; set; }
        public string CATCH_NUM { get; set; }
        public string CITY_ID { get; set; }
        public string CONS_ID { get; set; }
        public string CONS_TIT { get; set; }
        public string CONS_DEPT { get; set; }
        public string CONS_NAME { get; set; }
        public Nullable<System.DateTime> CONS_DATE { get; set; }
        public Nullable<System.DateTime> KEYIN_DATE { get; set; }
        public string NOTE { get; set; }
        public string US_X { get; set; }
        public string US_Y { get; set; }
        public string DS_X { get; set; }
        public string DS_Y { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string US_84X { get; set; }
        public string US_84Y { get; set; }
        public string DS_84X { get; set; }
        public string DS_84Y { get; set; }
        public System.Data.Entity.Spatial.DbGeometry coordinate { get; set; }
    }
}
